// Generated by view binder compiler. Do not edit!
package com.citsri.chargify.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.citsri.chargify.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMapBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final EditText developerMail;

  @NonNull
  public final RecyclerView evRecy;

  @NonNull
  public final ConstraintLayout main;

  private ActivityMapBinding(@NonNull ConstraintLayout rootView, @NonNull EditText developerMail,
      @NonNull RecyclerView evRecy, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.developerMail = developerMail;
    this.evRecy = evRecy;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMapBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMapBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_map, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMapBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.developer_mail;
      EditText developerMail = ViewBindings.findChildViewById(rootView, id);
      if (developerMail == null) {
        break missingId;
      }

      id = R.id.ev_recy;
      RecyclerView evRecy = ViewBindings.findChildViewById(rootView, id);
      if (evRecy == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityMapBinding((ConstraintLayout) rootView, developerMail, evRecy, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
