// Generated by view binder compiler. Do not edit!
package com.citsri.chargify.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RatingBar;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.citsri.chargify.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEvstationFullDetailsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView evMobileNo;

  @NonNull
  public final ImageView evPic;

  @NonNull
  public final TextView evStationLoc;

  @NonNull
  public final TextView evStationName;

  @NonNull
  public final RatingBar evStationRating;

  @NonNull
  public final TextView evStationStatus;

  @NonNull
  public final EditText feedback;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final EditText rateByCustomer;

  @NonNull
  public final Spinner statusList;

  private ActivityEvstationFullDetailsBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView evMobileNo, @NonNull ImageView evPic, @NonNull TextView evStationLoc,
      @NonNull TextView evStationName, @NonNull RatingBar evStationRating,
      @NonNull TextView evStationStatus, @NonNull EditText feedback, @NonNull ConstraintLayout main,
      @NonNull EditText rateByCustomer, @NonNull Spinner statusList) {
    this.rootView = rootView;
    this.evMobileNo = evMobileNo;
    this.evPic = evPic;
    this.evStationLoc = evStationLoc;
    this.evStationName = evStationName;
    this.evStationRating = evStationRating;
    this.evStationStatus = evStationStatus;
    this.feedback = feedback;
    this.main = main;
    this.rateByCustomer = rateByCustomer;
    this.statusList = statusList;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEvstationFullDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEvstationFullDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_evstation_full_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEvstationFullDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.ev_mobile_no;
      TextView evMobileNo = ViewBindings.findChildViewById(rootView, id);
      if (evMobileNo == null) {
        break missingId;
      }

      id = R.id.ev_pic;
      ImageView evPic = ViewBindings.findChildViewById(rootView, id);
      if (evPic == null) {
        break missingId;
      }

      id = R.id.ev_station_loc;
      TextView evStationLoc = ViewBindings.findChildViewById(rootView, id);
      if (evStationLoc == null) {
        break missingId;
      }

      id = R.id.ev_station_name;
      TextView evStationName = ViewBindings.findChildViewById(rootView, id);
      if (evStationName == null) {
        break missingId;
      }

      id = R.id.ev_station_rating;
      RatingBar evStationRating = ViewBindings.findChildViewById(rootView, id);
      if (evStationRating == null) {
        break missingId;
      }

      id = R.id.ev_station_status;
      TextView evStationStatus = ViewBindings.findChildViewById(rootView, id);
      if (evStationStatus == null) {
        break missingId;
      }

      id = R.id.feedback;
      EditText feedback = ViewBindings.findChildViewById(rootView, id);
      if (feedback == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.rate_by_customer;
      EditText rateByCustomer = ViewBindings.findChildViewById(rootView, id);
      if (rateByCustomer == null) {
        break missingId;
      }

      id = R.id.status_list;
      Spinner statusList = ViewBindings.findChildViewById(rootView, id);
      if (statusList == null) {
        break missingId;
      }

      return new ActivityEvstationFullDetailsBinding((ConstraintLayout) rootView, evMobileNo, evPic,
          evStationLoc, evStationName, evStationRating, evStationStatus, feedback, main,
          rateByCustomer, statusList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
