// Generated by view binder compiler. Do not edit!
package com.citsri.chargify.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RatingBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.citsri.chargify.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class EvStationCardViewBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView evStationLoc;

  @NonNull
  public final TextView evStationName;

  @NonNull
  public final ImageView evStationPic;

  @NonNull
  public final RatingBar evStationRating;

  @NonNull
  public final TextView evStationStatus;

  private EvStationCardViewBinding(@NonNull CardView rootView, @NonNull TextView evStationLoc,
      @NonNull TextView evStationName, @NonNull ImageView evStationPic,
      @NonNull RatingBar evStationRating, @NonNull TextView evStationStatus) {
    this.rootView = rootView;
    this.evStationLoc = evStationLoc;
    this.evStationName = evStationName;
    this.evStationPic = evStationPic;
    this.evStationRating = evStationRating;
    this.evStationStatus = evStationStatus;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static EvStationCardViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EvStationCardViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.ev_station_card_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EvStationCardViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.ev_station_loc;
      TextView evStationLoc = ViewBindings.findChildViewById(rootView, id);
      if (evStationLoc == null) {
        break missingId;
      }

      id = R.id.ev_station_name;
      TextView evStationName = ViewBindings.findChildViewById(rootView, id);
      if (evStationName == null) {
        break missingId;
      }

      id = R.id.ev_station_pic;
      ImageView evStationPic = ViewBindings.findChildViewById(rootView, id);
      if (evStationPic == null) {
        break missingId;
      }

      id = R.id.ev_station_rating;
      RatingBar evStationRating = ViewBindings.findChildViewById(rootView, id);
      if (evStationRating == null) {
        break missingId;
      }

      id = R.id.ev_station_status;
      TextView evStationStatus = ViewBindings.findChildViewById(rootView, id);
      if (evStationStatus == null) {
        break missingId;
      }

      return new EvStationCardViewBinding((CardView) rootView, evStationLoc, evStationName,
          evStationPic, evStationRating, evStationStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
